Uses torchmetrics for metric computation
CUNY-CL/yoyodyne pull request #284
Opened 2024-12-08 20:33 UTC by kylebgorman

Closes #158.

* Loss is computed as before, but streamlined somewhat.
* `torchmetrics`' implementation of exact match accuracy is lightly adapted. This does everything in tensor-land and should keep things on devices. My tests confirm that accuracy is EXACTLY what it was before.
* A `torchmetrics`-compatible implementation of symbol error rate (here defined as the edit distance divided by sum of target lengths) is inserted here. This is heavily documented and it is compatible with our existing implementation. The hot inner loop is still on CPU, but as mentioned in the documentation, this is probably the best option and I don't observe any obvious performance penalty when enabling this.
* We do away with the `evaluation` module altogether. Rather we treat the metrics objects as nullables living in the base class, a design adapted from UDTube.

The CLI interface is unimpacted, and my side-by-side shows the metrics are exactly the same as before this change.

2024-12-10 17:34 UTC, Adamits commented
Nice! 

> * Loss is computed as before, but streamlined somewhat.
> * `torchmetrics`' implementation of exact match accuracy is lightly adapted. This does everything in tensor-land and should keep things on devices. My tests confirm that accuracy is what it was before.

Cool, I think when we added our implementation, torchmetrics was requiring strings right? Glad ti see this.

> * A `torchmetrics`-compatible implementation of symbol error rate (here defined as the edit distance divided by sum of target lengths) is inserted here. This is heavily documented and it is compatible with our existing implementation. The hot inner loop is still on CPU, but as mentioned in the documentation, this is probably the best option and I don't observe any obvious performance penalty when enabling this. Note that the computation of the old one was not as normally defined and gave the number of edits per word, not the number of edits per gold target symbol.

So we go from a denominator of 1 (I am interpreting word as sequence, since we do not do pretokenization) to a denominator of the length of the gold symbols? Makes sense if so, but I cannot really remember what is standard.

> * We do away with the `evaluation` module altogether. Rather we treat the metrics objects as nullables living in the base class, a design adapted from UDTube.

Generally awesome!! Looking at the implementation, I am wondering why we replace the generic set of evals with specific metric attributes and metric booleans? What are the benefits of this (where I see the downsides as adding some bloat to the code, and lots of steps for including new metrics)?

> * Both loss and the metrics expect logits tensors to be of the shape B x target_vocab_size x seq_len, but the RNN library code wants it to be B x seq_len x target_vocab_size. I choose the former to be the "default" representation and let the RNN dimensionality be an implementational detail.

Does RNN library code mean for the `forward` function implemented in pytorch? I will look closer at the code, but my feeling is that it is conceptually better to try to maintain a consistent shape, and just reshape the tensor as close as possible to the function for which a different shape is needed.

2024-12-10 18:09 UTC, Adamits requested changes

2024-12-10 18:09 UTC, Adamits commented on yoyodyne/models/transducer.py
> +    def on_validation_epoch_start(self) -> None:
Shouldn't this be inherited? Or does some class in its inheritance override this so we have to override it back?

2024-12-10 18:09 UTC, Adamits commented on yoyodyne/models/transducer.py
> +    def validation_step(self, batch: data.PaddedBatch, batch_idx: int) -> None:
This also looks the same as the base method.

2024-12-10 18:09 UTC, Adamits commented on yoyodyne/models/transducer.py
> +    def on_validation_epoch_end(self) -> None:
ditto

2024-12-10 20:00 UTC, kylebgorman commented
> Nice!

Just to say: this isn't really ready for review yet. It depends on a lot of other small changes which I'll make first. I thought I could do it all in one go: I was wrong.

> Cool, I think when we added our implementation, torchmetrics was requiring strings right? Glad ti see this.

Yep. It wasn't too hard to make our own.

> So we go from a denominator of 1 (I am interpreting word as sequence, since we do not do pretokenization) to a denominator of the length of the gold symbols? Makes sense if so, but I cannot really remember what is standard.

Actually I mispoke here somewhat because I misread the code: the denominator was the length of the tensor; now it's the length of the string the tensor denotes.

> Generally awesome!! Looking at the implementation, I am wondering why we replace the generic set of evals with specific metric attributes and metric booleans? What are the benefits of this (where I see the downsides as adding some bloat to the code, and lots of steps for including new metrics)?

Benefits: data lives on the accelerator, like loss data does. I actually don't think the steps to add metrics is meaningfully more difficult than what we had previously, so I don't see any big downsides either. It also can be documented without much trouble. 

> > * Both loss and the metrics expect logits tensors to be of the shape B x target_vocab_size x seq_len, but the RNN library code wants it to be B x seq_len x target_vocab_size. I choose the former to be the "default" representation and let the RNN dimensionality be an implementational detail.
> 
> Does RNN library code mean for the `forward` function implemented in pytorch? I will look closer at the code, but my feeling is that it is conceptually better to try to maintain a consistent shape, and just reshape the tensor as close as possible to the function for which a different shape is needed.

I originally piloted with that. Most things in the Torch universe (including loss functions, but also everything in `torchmetrics`) assume that the first dimension is batch size and the second is vocabulary size (third is length), so it's basically a quirk of the library's RNN modules' forward pass that they swap vocabulary size and length. Since the output of those RNN modules needs some postprocessing anyways (run through a classifier, combined with pointer-generator information, softmaxed, etc.) it makes sense to me to transpose them back to the Torch default one time ("set it and leave it") during those steps. I think this can be done in just a few places and will be an improvement in useability. Transpositions are not, I assume, computationally expensive (I assume what they do internally is just change the "striding" logic by making a minor edit to some metadata in the tensors), but they are a big maintenance burden. 90% of my debugging here involves transpositions and making shape conform.

2024-12-10 20:01 UTC, kylebgorman commented on yoyodyne/models/base.py
> +    def compute_accuracy(self) -> bool:
I'll try `has_accuracy` instead.

2024-12-10 20:01 UTC, kylebgorman commented on yoyodyne/models/base.py
> +    def test_step(
Yeah it's something you can do in LightningCLI.

2024-12-23 20:56 UTC, Adamits commented
> > Nice!
> 
> Just to say: this isn't really ready for review yet. It depends on a lot of other small changes which I'll make first. I thought I could do it all in one go: I was wrong.
> 
> > Cool, I think when we added our implementation, torchmetrics was requiring strings right? Glad ti see this.
> 
> Yep. It wasn't too hard to make our own.
> 
> > So we go from a denominator of 1 (I am interpreting word as sequence, since we do not do pretokenization) to a denominator of the length of the gold symbols? Makes sense if so, but I cannot really remember what is standard.
> 
> Actually I mispoke here somewhat because I misread the code: the denominator was the length of the tensor; now it's the length of the string the tensor denotes.
> 
> > Generally awesome!! Looking at the implementation, I am wondering why we replace the generic set of evals with specific metric attributes and metric booleans? What are the benefits of this (where I see the downsides as adding some bloat to the code, and lots of steps for including new metrics)?
> 
> Benefits: data lives on the accelerator, like loss data does. I actually don't think the steps to add metrics is meaningfully more difficult than what we had previously, so I don't see any big downsides either. It also can be documented without much trouble.
> 
> > > * Both loss and the metrics expect logits tensors to be of the shape B x target_vocab_size x seq_len, but the RNN library code wants it to be B x seq_len x target_vocab_size. I choose the former to be the "default" representation and let the RNN dimensionality be an implementational detail.
> > 
> > 
> > Does RNN library code mean for the `forward` function implemented in pytorch? I will look closer at the code, but my feeling is that it is conceptually better to try to maintain a consistent shape, and just reshape the tensor as close as possible to the function for which a different shape is needed.
> 
> I originally piloted with that. Most things in the Torch universe (including loss functions, but also everything in `torchmetrics`) assume that the first dimension is batch size and the second is vocabulary size (third is length), so it's basically a quirk of the library's RNN modules' forward pass that they swap vocabulary size and length. Since the output of those RNN modules needs some postprocessing anyways (run through a classifier, combined with pointer-generator information, softmaxed, etc.) it makes sense to me to transpose them back to the Torch default one time ("set it and leave it") during those steps. I think this can be done in just a few places and will be an improvement in useability. Transpositions are not, I assume, computationally expensive (I assume what they do internally is just change the "striding" logic by making a minor edit to some metadata in the tensors), but they are a big maintenance burden. 90% of my debugging here involves transpositions and making shape conform.


Sorry for my delay. This mostly all makes sense to me. " 90% of my debugging here involves transpositions and making shape conform." -- this has typically been my experience in general when writing torch code :). I am mostly trying to suggest that having a yoyodyne default assumption of what shape tensors are in would be nice -- and I think would make it conceptually easier to visualize tensors as you code. If I follow correctly though, the decisions you made in reshaping sounds very reasonable.

2025-03-25 16:28 UTC, kylebgorman commented on yoyodyne/models/base.py
> -    eval_metrics: Set[evaluators.Evaluator]
To add a new metric you implement it in `metrics` and add it to the table, then you enable it in the base model in locations now clearly marked. I could imagine us getting one or two more metrics but certainly not a lot of them.

2025-03-25 16:42 UTC, kylebgorman commented on yoyodyne/models/transducer.py
> +    def on_validation_epoch_start(self) -> None:
Reverted, we don't need this.

2025-03-25 16:42 UTC, kylebgorman commented on yoyodyne/models/transducer.py
> +    def validation_step(self, batch: data.PaddedBatch, batch_idx: int) -> None:
It's not anymore, fixed.

2025-03-25 16:42 UTC, kylebgorman commented on yoyodyne/models/transducer.py
> +    def on_validation_epoch_end(self) -> None:
Removed because of redesign

2025-03-25 17:09 UTC, kylebgorman commented
I'm going to restart this PR because merging is a pain. But comments have been addressed.

2025-03-25 17:13 UTC, closed without merging